# Start validate task for provider csr
---
- name: Gather crypto session information
  ansible.utils.cli_parse:
    command: show crypto session
    parser:
      name: ansible.netcommon.pyats
  register: result

- name: Store session information
  ansible.builtin.set_fact:
    tunnel: "{{ result.parsed.interface[data.tunnel] }}"

- name: "Validate session status for tunnel - {{ data.tunnel }}"
  ansible.builtin.assert:
    that:
      - "{{ tunnel.session_status == data.session_status }}"
    fail_msg: "Tunnel {{ data.tunnel }} session-status is {{ tunnel.session_status }}"
    success_msg: "Tunnel {{ data.tunnel }} has passed session status validation!"
