---
- name: "Start network.vpn.validate role"
  ansible.builtin.include_role:
    name: network.vpn.validate
  vars:
    provider: azure
    configuration_file: azure.yaml

- name: "Include provider-specific validate tasks"
  ansible.builtin.include_tasks: "{{ item.name }}.yaml"
  loop: "{{ providers }}"
