---
authors:
  - Nilashish Chakraborty (@NilashishC)
dependencies:
  "cisco.ios": ">=6.0.0"
  "azure.azcollection": ">=1.13.0"
  "community.aws": ">=4.2.0"
license_file: LICENSE
name: vpn
namespace: network
description: Ansible Collection to build, maintain and validate VPN tunnels across cloud providers and network appliances.
readme: README.md
repository: https://github.com/redhat-cop/network.vpn
issues: https://github.com/redhat-cop/network.vpn/issues
tags: [cisco, aws, azure, vpn, cloud, networking]
version: 3.0.1
